apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniserver.fullname" . }}
  labels:
    {{- include "miniserver.labels" . | nindent 4 }}
data:
{{ toYaml .Values.service.env | indent 2 }}
