apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniserver.fullname" . }}
  labels:
    {{- include "miniserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # @mati: This is the port that is exposed for ingress
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
  {{- include "miniserver.selectorLabels" . | nindent 4 }}
