name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/matias-linares-ceg/miniserver
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        _version=$(date +%s)
        echo "Building image ${DOCKER_IMAGE}:${_version}"
        docker build . --file Dockerfile --tag "${DOCKER_IMAGE}:${_version}" --tag "${DOCKER_IMAGE}:latest"
