name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/matias-linares-ceg/miniserver
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        _version=$(git rev-parse --short HEAD)
        echo "Building image ${DOCKER_IMAGE}:${_version}"
        docker build . --file Dockerfile --tag "${DOCKER_IMAGE}:${_version}" --tag "${DOCKER_IMAGE}:latest"
    - name: Push to container registry
      run: |
        echo ${{ github.token }} | docker login ghcr.io -u matias-linares-ceg --password-stdin
        _version=$(git rev-parse --short HEAD)
        docker push --all-tags ${DOCKER_IMAGE}

