name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ghcr.io/matias-linares-ceg/miniserver

    permissions:
      packages: write
      contents: read
      actions: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        _version=$(git rev-parse --short HEAD)
        echo "Building image ${DOCKER_IMAGE}:${_version}"
        docker build . --file Dockerfile --tag "${DOCKER_IMAGE}:${_version}" --tag "${DOCKER_IMAGE}:latest"
    - name: Push to container registry
      run: |
        echo ${{ github.token }} | docker login ghcr.io -u matias-linares-ceg --password-stdin
        _version=$(git rev-parse --short HEAD)
        docker push --all-tags ${DOCKER_IMAGE}

    - name: Trigger workflow
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        _version=$(git rev-parse --short HEAD)
        echo version: $_version
        curl -X POST -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/matias-linares-ceg/actions/dispatches \
             -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"version\": \"$_version\"}}"
